# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Pierre Chrzanowski
tagline:          ' - ma part du web'
description:      'Site personnel de Pierre Chrzanowski'
url:              http://pzwsk.eu

author:
  name:           'Pierre Chrzanowski'
  url:            https://twitter.com/pzwsk

paginate:         5
